apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  clusterIP: None
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 6379 # service port
    targetPort: 6379 # container port
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 6379  # service port
    targetPort: 6379  # container port
---
#StatefulSet Resource
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  # Deployment set labels
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  replicas: 2
   # These are the labels replica set use to create pod replicas, this should match pod labels
  serviceName: "redis-headless" # this should be headless service 
  selector:
    matchLabels:
      component: redis
      project: roboshop
      tier: database

  # This is pod definition
  template:
    metadata:
      labels:
        component: redis
        project: roboshop
        tier: database
    spec:
      containers:
      - name: redis
        image: redis:7.0
        volumeMounts:
        - name: redis-data
          mountPath: /data

    # This is nothing but PVC, you can directly create here
  volumeClaimTemplates:
  - metadata:
      name: redis-data
      namespace: roboshop
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 2Gi


